### ISSUE TITLE
代码结构上的重构建议

### ISSUE THREAD

**Issue by gejiawen** [tangzhengwen/base#2]
目前的代码就一个文件，这个不太利于开发和维护，也不太利于多人维护。

建议按照功能将文件拆分，类似于`core+plugin`的模式。

第二点就是类库中引入构建系统和单元测试模块。

**Comment by tangzhengwen** [comment]
结构重构完毕，单元测试正在写测试代码。

**Comment by gejiawen** [comment]
代码好像还没拆分嘛？

**Comment by tangzhengwen** [comment]
base.js 定位就是一个 core 啊，怎么拆分？
